# Use the Midnight theme from GitHub Pages
remote_theme: pages-themes/midnight@v0.2.0

# Plugins list
plugins:
  - jekyll-remote-theme # Enable the remote theme plugin

# Site settings
title: Cybersecurity KQL Queries
description: "A collection of KQL queries for hunting CVEs and general cybersecurity tasks."
url: "https://spicys4l.github.io"  # Your GitHub Pages URL
baseurl: ""  # No subdirectory (unless your site is in one)

# Author info
author:
  name: Nery

# Navigation links
nav:
  - name: "Home"
    link: "/"
  - name: "CVE-2025-21298"
    link: "/cve-2025-21298.html"
  - name: "KQL Queries"
    link: "/kql-queries.html"  # You can create a new page for general KQL queries
  - name: "About"
    link: "/about.html"  # Optional About page

# Optional: Social links (excluding Twitter and email)
social:
  github: "https://github.com/spicys4l"
  linkedin: "https://www.linkedin.com/in/nery-salguero/"
